/*************************************************************************************************
* This file is part of the apex-limit-framework project, released under the MIT License.             *
* See LICENSE file or go to https://github.com/agarwalsanchit1/apex-events-trigger-framework for full license details. *
*************************************************************************************************/

global virtual class IllegalStateException extends Exception {}