/*************************************************************************************************
* This file is part of the apex-limit-framework project, released under the MIT License.             *
* See LICENSE file or go to https://github.com/agarwalsanchit1/apex-criterium for full license details. *
*************************************************************************************************/

@IsTest
private class SampleBenchMarkerTemplateTest {

    @isTest
    private static void runBenchMarkCodeTest() {
        (new SampleBenchMarkerTemplate()).runBenchMarkCode();
    }
}