/*************************************************************************************************
* This file is part of the apex-criterium project, released under the MIT License.             *
* See LICENSE file or go to https://github.com/agarwalsanchit1/apex-criterium for full license details. *
*************************************************************************************************/

global abstract class ApexLimitsAppConstants {

    global static Integer AUTO_COMMIT_METRICS_ENTRY_MIN_RANGE = 30;
    global static Integer AUTO_COMMIT_METRICS_ENTRY_MAX_RANGE = 50;   
}